name = "QuantumCliffordPlots"
uuid = "4eeed724-23be-436c-a322-a8540588cc9f"
authors = ["Stefan Krastanov <stefan@krastanov.org> and contributors"]
version = "0.1.3"

[deps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Quantikz = "b0d11df0-eea3-4d79-b4a5-421488cbf74b"
QuantumClifford = "0525e862-1e90-11e9-3e4d-1b39d7109de1"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"

[compat]
Makie = "0.16"
Quantikz = "1.1.2"
QuantumClifford = "0.5, 0.4"
RecipesBase = "1.0"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
